drivers: video: disable literal-conversion
Fixing this breaks conversions more

drivers/video/fbdev/exynos/decon_8890/decon_reg_8890.c:2008: undefined reference to `__nedf2'
drivers/video/fbdev/exynos/decon_8890/decon_reg_8890.c:2014: undefined reference to `__floatunsidf'
drivers/video/fbdev/exynos/decon_8890/decon_reg_8890.c:2014: undefined reference to `__nedf2'
drivers/video/fbdev/exynos/decon_8890/decon_reg_8890.c:2018: undefined reference to `__fixdfdi'
drivers/video/fbdev/exynos/decon_8890/decon_reg_8890.c:2019: undefined reference to `__fixdfdi'
drivers/video/fbdev/exynos/decon_8890/decon_reg_8890.c:2020: undefined reference to `__fixdfdi'
drivers/video/fbdev/exynos/decon_8890/decon_reg_8890.c:2021: undefined reference to `__fixdfdi'
drivers/video/fbdev/exynos/decon_8890/decon_reg_8890.c:2022: undefined reference to `__fixdfdi'

TODO : actually fix later